version: '3.4'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sortiment/:/app/sortiment/
      - ./sortiment/uploads/:/app/uploads/
    environment:
      - DEBUG=True
    depends_on:
      - db
    command: "./start_dev.sh"

  tailwind:
    build:
      context: .
      target: cssbuild
    volumes:
      - ./sortiment:/app/sortiment
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./package.json:/app/package.json
    tty: true

volumes:
  postgres_data:
