version: '3.4'
services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./sortiment/:/app/
    depends_on:
      - db
    command: "./start_dev.sh"

volumes:
  postgres_data:
