# Generated by Django 4.0.3 on 2022-03-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_ean_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
