# Generated by Django 4.1.5 on 2023-01-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="ip",
            field=models.GenericIPAddressField(default=""),
            preserve_default=False,
        ),
    ]
