# Generated by Django 4.1.5 on 2023-02-01 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0009_product_is_dummy"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouseevent",
            name="retail_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                verbose_name="odbytová cena / ks",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="skladová cena / ks"
            ),
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="produkt",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="quantity",
            field=models.IntegerField(verbose_name="počet"),
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="dátum a čas"),
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="type",
            field=models.IntegerField(
                choices=[
                    (0, "import"),
                    (1, "purchase"),
                    (2, "transfer in"),
                    (3, "transfer out"),
                    (4, "discard"),
                    (5, "correction"),
                ],
                verbose_name="typ dokladu",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="používateľ",
            ),
        ),
        migrations.AlterField(
            model_name="warehouseevent",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.warehouse",
                verbose_name="sklad",
            ),
        ),
    ]
