# Generated by Django 4.1.5 on 2023-02-01 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_warehouseevent_retail_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="čiarový kóď"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="obrázok"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_dummy",
            field=models.BooleanField(
                default=False, verbose_name="jednorázový predmet"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_unlimited",
            field=models.BooleanField(verbose_name="neobmedzený predmet"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=128, verbose_name="názov"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="predajná cena"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="store.tag", verbose_name="tagy"
            ),
        ),
        migrations.AlterField(
            model_name="warehousestate",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="produkt",
            ),
        ),
        migrations.AlterField(
            model_name="warehousestate",
            name="quantity",
            field=models.IntegerField(verbose_name="počet"),
        ),
        migrations.AlterField(
            model_name="warehousestate",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=16, verbose_name="skladová cena"
            ),
        ),
        migrations.AlterField(
            model_name="warehousestate",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.warehouse",
                verbose_name="sklad",
            ),
        ),
    ]
