# Generated by Django 4.1.5 on 2023-02-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_alter_product_barcode_alter_product_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="barcode",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="čiarový kód"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_dummy",
            field=models.BooleanField(
                default=False, verbose_name="jednorazový predmet"
            ),
        ),
    ]
