# Generated by Django 4.1.7 on 2023-10-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_reset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.FileField(null=True, upload_to="", verbose_name="obrázok"),
        ),
    ]
