# Generated by Django 5.0.6 on 2024-07-03 21:38

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_product_image"),
    ]

    operations = [UnaccentExtension()]
