# Generated by Django 4.1.5 on 2023-02-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_sortimentuser_is_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlog",
            name="is_purchase",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
