# Generated by Django 4.1.5 on 2023-03-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_sortimentuser_barcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlog",
            name="message",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
