# Generated by Django 4.1.7 on 2023-04-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_creditlog_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortimentuser',
            name='shortcut',
            field=models.CharField(blank=True, max_length=1, verbose_name='klavesová skratka'),
        ),
    ]
