# Generated by Django 5.1.4 on 2025-10-02 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_auto_20240703_2338"),
        ("users", "0007_creditlog_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditlog",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.warehouse",
                verbose_name="sklad",
            ),
        ),
    ]
